host:
    ip: 0.0.0.0
    port: 8000
db:
    uname: root
    passwd: rootroot
    dbname: ctf
    ip: 127.0.0.1
    port: 13306
    str: ""
    cname: mysql439138121
admin:
    uname: admin
    passwd: admin
str:
    key: AAAAAAAAAA
